title: Ben Bastian's Blog
description: >-
  Ben Bastian's blog about software, AI, and other things.
baseurl: "" # the subpath, e.g. /blog
url: "http://www.bpbastian.com"
twitter_username: sagelywizard
github_username: sagelywizard

plugins:
  - jekyll-feed
  - jekyll-postcss
postcss:
  cache: false
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge